[project]
name = "omlsp"
version = "0.0.1"
description = "One More Little SQL Parser"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "aiohttp==3.12.14",
  "loguru==0.7.3",
  "sqlglot==27.1.0"
]

[dependency-groups]
dev = [
  "ruff>=0.12.3"
]